import 'bootstrap/dist/css/bootstrap.min.css';
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from '@/components/main-header';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ITS Incom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MainHeader />
        {children}
        <Footer />
      </body>
    </html>
  );
}
