// layout.js
// "use client"; // Remove this line

import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from '@/components/main-header';
import Footer from '@/components/footer';
import { AuthProvider } from '@/utils/AuthContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ITS Incom",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MainHeader />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
